### ISSUE TITLE
joined list syntax fails

### ISSUE THREAD

**Issue by iros** [bocoup/deployment-workflow#14]
In directives like this:

```
- name: backup existing nginx config files
  shell: cp {{item.file}} {{item.file}}.backup
  args:
    chdir: "{{item.directory}}"
  with_items: nginx_confs + nginx_shared
```

I was unable to execute these commands because the + was combining the lists into something that was not one large flattened list.

I changed it to use with_flattened:

```
- name: ensure nginx config files exist
  shell: touch {{item.directory}}/{{item.file}}
  args:
    creates: "{{item.directory}}/{{item.file}}"
  with_flattened:
    - nginx_confs
    - nginx_shared
```

I have Vagrant 1.7.2 and ansible 1.8
