### ISSUE TITLE
add a playbook for configuring users

### ISSUE THREAD

**Issue by tkellen** [bocoup/deployment-workflow#22]
It should run these commands:
https://github.com/endpoints/endpoints/blob/master/deploy/ansible/roles/configure/tasks/main.yml#L24-L45

...be configured by this format of a yml file:

``` yml
users:
  - name: john_doe
    real_name: John Doe
    state: present
    shadow_pass: $1$foobarba$leTBLi1qiudh69.gIeaF/0
    groups: sudo
    shell: /bin/bash
    keys:
      - state: present
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDn6RKYQrau3fOgzcIumuQcxvpfs6xrueXv+r5Es/yowPpub9UcLaeJWHSgapv70+jdj3Z4molXvyeDifu6G5hE/89bJTkIJ8eFYGryRpJmwT7hnnJHSgZWJu62zcLbVGhGoNwTP1d4ah8rBgvd5rt4MZobLZa2MiTteLU9krDVUJuPMjLFN9kyjwWRPFt9F+HY3JltOJbg2kyJZBpijy9idxDs++AJ37IJiXlbykn7gylR9JWoTaagGXkPZPtGQ4r9gF9mAUsSqU1JTaLG3HpXVrxgCQEWbAbRDs7z7GJ1mqN0h6/XVwyQpBvgBVk8VJRlZ+Wll9a80+Q/NH5qau8v
```

...and the command to generate a shadow pass is:

```
openssl passwd -salt 'ENTER_ANYTHING_WITHOUT_SPACES_HERE' -1 'MYPASSWORDHERE'
```
