### ISSUE TITLE
add playbook for adding self to vagrant box as a passwordless sudoer

### ISSUE THREAD

**Issue by tkellen** [bocoup/deployment-workflow#27]
If this is run on the vagrant machine during provisioning, the user will be able to run the same ansible commands they run on a production server directly on the vagrant box:

``` yaml
- hosts: vagrant
  sudo: yes
  vars:
    user: "{{ lookup('env', 'USER') }}"
    public_key_path: ~/.ssh/id_rsa.pub
  tasks:
    - name: add the current user
      user: name={{user}} group=sudo shell=/bin/bash

    - name: add the current user's public key
      authorized_key: user={{user}} key="{{ lookup('file', public_key_path) }}"
```
