### ISSUE TITLE
Make task formatting more consistent.

### ISSUE THREAD

**Issue by cowboy** [bocoup/deployment-workflow#39]
Reformat tasks with options defined like this:

```yaml
- name: ensure users are synced
  user: name={{item.name}}
    force=yes
    remove=yes
    password={{ item.shadow_pass | default(omit) }}
    state={{ item.state | default(omit) }}
    shell={{ item.shell | default("/bin/bash") }}
    groups={{ item.groups | default("sudo") }}
  with_items: users
```

To this style:

```yaml
- name: ensure users are synced
  user:
    name: "{{item.name}}"
    force: yes
    remove: yes
    password: "{{ item.shadow_pass | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    shell: "{{ item.shell | default("/bin/bash") }}"
    groups: "{{ item.groups | default("sudo") }}"
  with_items: users
```

Also, define only one option per line, such that this:

```yaml
- name: check if specified commit sha has already been deployed
  stat: path={{base_path}}/{{sha.stdout}} get_checksum=no get_md5=no
  register: sha_dir
```

Would become:

```yaml
- name: check if specified commit sha has already been deployed
  stat:
    path: "{{base_path}}/{{sha.stdout}}"
    get_checksum: no
    get_md5: no
  register: sha_dir
```
