### ISSUE TITLE
CI based deploys

### ISSUE THREAD

**Issue by reconbot** [bocoup/deployment-workflow#87]
Hookshot is great, but I think it would be nice to leverage a CI to do the deploy on a successful build of a branch (eg master deploying to a staging environment).
- Has anyone successfully done this with this workflow?
- Do we have/want instructions about this in particular?

**Comment by tkellen** [comment]
Huge :+1: from me on hooking this up.

**Comment by cowboy** [comment]
At the very least, it'd be great to document how to set it up in the wiki!

**Comment by reconbot** [comment]
This doesn't work. I get an error code of 1 when using `run-playbook` and an error code of `3` if I call `ansible-playbook` directly. I was getting ssh errors, and other kinds of things, but I solved those. I'm stumped. I'm no longer getting output, only error codes.

# How to get travis to deploy master to your staging environment (not yet working)

## Notes
 - Faster container based build is blocked by https://github.com/travis-ci/apt-source-whitelist/issues/183
 - Opened https://github.com/travis-ci/travis-ci/issues/5833 as that caused a ton of debugging 
 - This might have been used for the ssh key https://docs.travis-ci.com/user/private-dependencies/ instead of generating our own keypair

## Step by Step

 - generate a keypair for a deployer user
 - add a deployer user to the users task only to run in staging
 - (manual) run the configure playbook on staging to add the user to the server
 - (manual) add deployer to /etc/sudoers as a passwordless sudoer (after group definitions) `deployer ALL=(ALL:ALL) NOPASSWD: ALL`
 - (manual) modify run-playbook.sh to not ask the deployer user for it's sudo password
 - put the private key somewhere eg `./deploy` (don't commit this key)
 - [Encrypt the file](https://docs.travis-ci.com/user/encrypting-files/) eg `travis encrypt-file deploy/deployer.key deploy/deployer.key.enc --add`
 - commit the changes to travis.yml, the deploy/deployer.key.enc
 - add a call to `run-playbook.sh` to the `deploy` section of your `.travis.yml`

## Example .travis.yml

language: node_js
node_js: '4'
sudo: true
addons:
  ssh_known_hosts:
   - example.com
before_install:
  - openssl aes-256-cbc -K $enc_var -iv $enc_var_iv -in deploy/deployer.key.enc -out deploy/deployer.key -d
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install -y ansible
deploy:
  provider: script
  script:
    - ssh-add deploy/deployer.key && deploy/run-playbook.sh deploy staging --user=deployer
  on:
    branch: deploy-from-travis

## Example users.yml task addition
```yml

- name: ensure deploy user in staging
  user:
    name: deployer
    force: yes
    remove: yes
    password: omit
    state: present
    shell: /bin/bash
  authorized_key:
    user: deployer
    key: "{{deploy_user_key}}"
    state: present
    exclusive: yes
  when: env == "staging"

```
